"""Remove Board, link columns directly to spaces

Revision ID: 005
Revises: 004
Create Date: 2025-02-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, None] = '033e2f6844e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add space_id column to columns table (nullable initially)
    op.add_column('columns', sa.Column('space_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # 2. Create foreign key constraint for space_id
    op.create_foreign_key('fk_columns_space_id', 'columns', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    
    # 3. Populate space_id from the board's space_id for all existing columns
    op.execute("""
        UPDATE columns c
        SET space_id = b.space_id
        FROM boards b
        WHERE c.board_id = b.id
    """)
    
    # 4. Make space_id NOT NULL after population
    op.alter_column('columns', 'space_id',
        existing_type=postgresql.UUID(as_uuid=True),
        nullable=False
    )
    
    # 5. Drop the foreign key and column for board_id
    op.drop_constraint('columns_board_id_fkey', 'columns', type_='foreignkey')
    op.drop_column('columns', 'board_id')
    
    # 6. Drop the boards table
    op.drop_table('boards')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Recreate boards table
    op.create_table('boards',
        sa.Column('id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=False),
        sa.Column('space_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name='boards_space_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='boards_pkey')
    )
    
    # 2. Add board_id back to columns
    op.add_column('columns', sa.Column('board_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    
    # 3. Create foreign key for board_id
    op.create_foreign_key('columns_board_id_fkey', 'columns', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    
    # 4. Drop space_id from columns
    op.drop_constraint('fk_columns_space_id', 'columns', type_='foreignkey')
    op.drop_column('columns', 'space_id')
    
    # Note: Downgrade cannot restore data relationships since boards were deleted.
    # The board_id column will be NULL for all columns after downgrade.
    
    # ### end Alembic commands ###
