"""Add timezone to space created_at

Revision ID: 033e2f6844e6
Revises: 68bf324427c9
Create Date: 2026-02-01 21:44:47.899985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '033e2f6844e6'
down_revision: Union[str, None] = '68bf324427c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
