"""add_comment_edit_delete_fields

Revision ID: 69afc0502192
Revises: 002_add_location
Create Date: 2026-01-29 20:47:04.237241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69afc0502192'
down_revision: Union[str, None] = '002_add_location'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('comments', sa.Column('is_edited', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_deleted')
    op.drop_column('comments', 'is_edited')
    # ### end Alembic commands ###
